name: python_and_r
channels:
  - defaults
dependencies:
  - ipykernel=6.4.1
  - ipython=7.31.1
  - matplotlib=3.5.0
  - numpy=1.21.5
  - pandas=1.3.4
  - pip=21.2.4
  - python=3.7.11
  - r-base=3.6.1
  - r-irkernel=0.8.15
  - r-robustgasp=0.5.7
  - rpy2=2.9.4